version: '3.8'

services:
  jupyterbook:
    build: .
    ports:
      - "8040:8040"
    volumes:
      - ./docs:/app/docs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
