name: Deploy Jupyter Book

on:
  push:
    branches:
      - main
      - docs #to be removed later

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book ghp-import

      - name: Build the Jupyter Book
        run: jupyter-book build docs/

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f docs/_build/html
