# .github/workflows/codespell.yml

name: Codespell Linter

on:
  pull_request:
    paths:
      - '**/*.py'
      - '**/*.md'
      - '**/*.txt'
  push:
    branches:
      - main

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Codespell
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install codespell

    - name: Run Codespell
      run: |
        codespell . --skip="*.pyc,*.git,*.svg" --check-filenames --check-hidden
